### ISSUE TITLE
Getting array for single values

### ISSUE THREAD

**Issue by zecar** [pillarjs/multiparty#165]
```js
app.post('*', function(req, res, next){
	var form = new multiparty.Form();
	console.log(req.body);
	form.parse(req, function(err, fields, files){
		console.log(req.body, fields, err, files);
		req.uploadFiles = files || [];
		next();
	})
})
```

this is the server part
I'm using postman to test.
This is the body
[http://imgur.com/Jcjd0rg](url)
There are no headers set

And I get this for the fields
```js
{
	message: [ 'Test1' ]
}
```
Am I doing something wrong? I want to get message: 'Test1' not an array with a value

**Comment by dougwilson** [comment]
Hi @zecar that is how it works, correct. From the readme:

> fields is an object where the property names are field names and the values are arrays of field values.

This is  because you can send the same field name over and over again in a multipart request, and rather than require you to check `Array.isArray` for ever field you're about to access, they are always arrays. You can just use `[0]` to get the first occurrence if that's all you ever want to access.
