### ISSUE TITLE
First field is always missing

### ISSUE THREAD

**Issue by Overdrivr** [pillarjs/multiparty#176]
When sending multiple text fields + a file, the first field is systematically missing after parsing.

This is the curl command I'm sending to poke the API

```
curl -i -H \
-F interval=5 \
-F scriptname=myscript \
-F unit=m \
-F archive=@example-slack-push-04.tar.gz \
http://localhost:3000/api/Scripts/
```
So, three text fields (interval, scriptname and unit) and one file (archive)

This is the code I am using to parse the request (nothing fancy here)

```
var parser = new multiparty.Form();
parser.parse(req, function(err, fields, files) {
    if (err) return next(err);
    console.log(Object.keys(fields));
    console.log(fields)
    console.log(files)
});
```
Output
```
[ 'scriptname', 'unit' ]
{ scriptname: [ 'myscript' ], unit: [ 'm' ] }
{ archive:
   [ { fieldName: 'archive',
       originalFilename: 'example-slack-push-04.tar.gz',
       path: 'C:\\Users\\Bart\\AppData\\Local\\Temp\\kYpmRI5aP7hH831RpooY9-JH.gz',
       headers: [Object],
       size: 803 } ] }
```
I only receive the second and third text field, not the first one.

Is there an issue with my code or curl request ?

**Comment by dougwilson** [comment]
Hi @Overdrivr the issue is with your cURL request. On your first line, you are ending it with `-H`, which is telling cURL the thing after it is a header to send in the request. This causes cURL to send a header "-F" and then it thinks interval=5 is the URL to try. When that URL fails, it then moves on the to next URL, the localhost one. Just remove the `-H` and it works fine. Here is the full, working cURL
```
curl -i \
-F interval=5 \
-F scriptname=myscript \
-F unit=m \
-F archive=@example-slack-push-04.tar.gz \
http://localhost:3000/api/Scripts/
```

I hope that helps!
