### ISSUE TITLE
[v4.1.3] Unable to upload certificate using Internet Explorer 11

### ISSUE THREAD

**Issue by ninox92** [pillarjs/multiparty#199]
multiparty:
4.1.3

When submitting a form containing using IE11:
1. A file AND
2. A text inputfield

I receive the following error:
``` Expected alphabetic character, received 55 ```

Other browsers like Firefox and Chrome work fine

**Comment by dougwilson** [comment]
I'll take a look. Can you provide a copy of the HTML form you are using to do the upload? That way I'll have the same field names and ordering.

**Comment by ninox92** [comment]
I stripped the html form down to its minimal form.

```html
<form action="/endpoint" method="POST" enctype="multipart/form-data" data-multipartsubmit>

  <input type="file" name="certificate" required />

  <input type="password" name="ssl-passphrase">
  <label for="ssl-passphrase">Password:</label>

  <button type="submit" class="mdl-button">submit</button>

</form>
```

**Comment by dougwilson** [comment]
Hi @ninox92 sorry for the delay. I got a hold of a machine with IE11 on it and I used that HTML you posted as the page and put it in the example at https://github.com/pillarjs/multiparty#usage since you didn't provide what the server side should look like. I then typed in the password "foo" and choose a jpeg file and clicked submit and everything was good without error, so I'm not sure what the issue is off-hand.

Are there any additional details you can provide the help me get the same result? If you use the same code from the readme and your HTML does it work for you?

**Comment by dougwilson** [comment]
Closing due to no response.
