### ISSUE TITLE
Order of parts - fields vs files

### ISSUE THREAD

**Issue by msageryd** [pillarjs/multiparty#225]
I'm sorry to open a similar issue yet again. I would love some pointers on how to solve this.

Stackoverflow didn't like my question, or maybe it's written unclearly:
https://stackoverflow.com/questions/61222588/multipart-form-order-of-fields-files

My multiparty-question:
I sometimes receive multipart emails via Sendgrid where the files arrive before the fields. Is it really necessary to buffer the received files in order to ensure that I get hold of the fields before processing the files?

I don't know enough of streams and multipart forms. 

Is everything (the complete multipart form) sent as a single stream? In that case I suppose I just HAVE to buffer files if they arrive before the fields.

If the files and fields are somehow separated in separate streams It would seem possible to pause the file stream until all fields are received.

**Comment by dougwilson** [comment]
> Is everything (the complete multipart form) sent as a single stream?

Exactly. This is because this processes a single HTTP request. And one http request is just a single byte stream. So the order in which the client sends the bytes to the server will be how they show up in this module. If the client sends 5kb of files first and then the fields, well, there is no solution the server side can do in order to not buffer those 5kb somewhere in order to get to the fields and still have the files on hand.

**Comment by msageryd** [comment]
Thank you Doug!
At last I'm getting it. It's much easier to build stuff when you know whats going on with other stuff =)

My solution:
99% of the time I get fields before files. I will simply handle the edge cases by buffering locally in memory while awaiting the fields. I'll create log posts for when this happens so I can keep an eye on it and tweak the concept if needed.

I.e. 
If I have fields when files arrive -> pipe files to S3
Else -> stream to local buffer and then pipe to s3 when fields has arrived
