### ISSUE TITLE
I got '[object Object]' when passing field value as Blob type？

### ISSUE THREAD

**Issue by viprespro** [pillarjs/multiparty#248]
This is how i organize form data  as below，but I got '[object Object]'  in the chunk field, is that a debug or something, i expected to get file object, what should i do get it right? tks.

![01](https://user-images.githubusercontent.com/38908500/178896056-92ce0380-ad49-4a72-8915-254fdafc1fa8.png)
![02](https://user-images.githubusercontent.com/38908500/178896073-2cb67f7a-f21e-4a97-91cc-1885aad7eccf.png)
![03](https://user-images.githubusercontent.com/38908500/178896089-df35460d-475b-4acd-a908-330b7e5fc671.png
![04](https://user-images.githubusercontent.com/38908500/178896987-7222f832-dd6e-4180-8834-49376481be42.png)

**Comment by dougwilson** [comment]
Hi @viprespro sorry you are having trouble. According to your screenshot, `chunk` variable is not a `Blob` object, but instead an object with a `file` property that has a `Blob` value. If this is the case, then yes, the web browser is sending your server a field with the contents of `[object Object]` instead of the blob contents.

Unfortunately without you providing all the code, I am just guessing.

You can try changing your client code to `formData.append('chunk', chunk.file)` in case my guess is correct. If that does not fix your issue, you'll need to send enough code so I can reproduce the issue.

**Comment by viprespro** [comment]
> 

Thanks for your suggestion, u were right, i checkd the `chunk ` object, it does have a `file` property. I tried the code ` formData.append('chunk', chunk.file)`, issue fixed. Thanks again!
