### ISSUE TITLE
Parse name as array

### ISSUE THREAD

**Issue by noosxe** [pillarjs/multiparty#81]
Is there any way to make multiparty properly parse field names like title[en] and return the value as {title: { en: 'value' }} ?

**Comment by MarkAndrewJohnson** [comment]
I've ended up arriving here due to also wondering if there was a way to have multiparty not convert every parameter to an array even if it wasn't passed as form properties as an array.  It looks like the above solution may help.  With the frameworks I've been using including Express based ones I've yet to see request parameters (req.body, req.query, etc) all being converted to arrays anywhere else.  Whilst I understand there would be breaking changes to .parse() it could also be possible to look at an options[] parameter or single option to only populate each as an array if the attribute names ends in[].
